bundler_args: --without development --path vendor/bundle
script:
  - bundle exec rake travis:setup
  - bundle exec rake db:reset db:setup db:migrate db:test:prepare
  - bundle exec rake spec
language: ruby
before_install:
  - gem install bundler
before_script:
  - "cp config/database.sample.yml config/database.yml"
  - "cp config/initializers/secret_token.rb.sample config/initializers/secret_token.rb"
  - "cp config/settings/test.sample.yml config/settings/test.yml"
script: "RAILS_ENV=test bundle exec rake db:drop db:create db:migrate spec"
rvm:
  - 1.9.3
