development:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: triglav_development
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: triglav_test
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: triglav
  host: localhost
